services:
  mysql:
    image: mysql:8.4
    container_name: agendarhorario-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendarhorario
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: America/Sao_Paulo
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uapp', '-papp']
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: agendarhorario-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: agendarhorario-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

volumes:
  mysql_data:
  redis_data:
